### ISSUE TITLE
"Stateful session" support

### ISSUE THREAD

**Issue by sztomi** [ducaale/ht#47]
This is a broad, open-ended question. When I'm using a tool like `ht` with an API that requires authentication and several headers, I find myself struggling to manage that state. My best answer is I set environment variables that I use in the URL for the authentication, frequently go back in the shell history to edit URLs etc. If there is a cookie needed it's even more complicated. Same goes for setting non-standard headers. 

GUI tools like [Insomnia](https://insomnia.rest/) allow managing this in projects which reduces this pain, but requires using a GUI for a task that's (in my experience) a better fit for the terminal. 

So here is my question. Is there a reasonable way to implement some kind support for stateful sessions in ht, that's perhaps applied and mutated automatically when found in the current dir? (a bit like a browser). For example:

```
# .ht.session
base_url: "https://my-test-api.com/api
headers:
  Content-Type: "application/json"
  X-My-Specific-Header: "That value"

auth:
  token: "Bearer d2h5IHdvdWxkIHlvdSB0YWtlIHRoZSB0aW1lIHRvIGRlY29kZSB0aGlz"
```

and then used like: 

```
$ ht get /v2/user
Using .ht.session
... dump user json ... 
```

The above a very raw demonstration that hopefully communicates the idea - not the concrete proposal itself.

There is of course a fine balance between explicitness and ease of use. Hiding too much information can lead to surprising behavior. But I still feel there could be a reasonable middle ground. Any thoughts?
